[2024-03-20T14:01:18.294+0000] {processor.py:161} INFO - Started process (PID=145) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2024-03-20T14:01:18.307+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2024-03-20T14:01:18.315+0000] {logging_mixin.py:188} INFO - [2024-03-20T14:01:18.314+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2024-03-20T14:01:33.433+0000] {processor.py:842} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2024-03-20T14:01:33.482+0000] {processor.py:183} INFO - Processing /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py took 15.215 seconds
[2024-03-20T14:03:37.118+0000] {processor.py:161} INFO - Started process (PID=265) to work on /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2024-03-20T14:03:37.219+0000] {processor.py:830} INFO - Processing file /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py for tasks to queue
[2024-03-20T14:03:37.294+0000] {logging_mixin.py:188} INFO - [2024-03-20T14:03:37.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py
[2024-03-20T14:04:24.866+0000] {logging_mixin.py:188} INFO - [2024-03-20T14:04:24.714+0000] {timeout.py:68} ERROR - Process timed out, PID: 265
[2024-03-20T14:04:24.890+0000] {logging_mixin.py:188} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7fc8a454c550>
[2024-03-20T14:04:24.911+0000] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-03-20T14:04:24.913+0000] {logging_mixin.py:188} WARNING -   File "/usr/local/lib/python3.8/weakref.py", line 345, in remove
[2024-03-20T14:04:24.969+0000] {logging_mixin.py:188} WARNING -     def remove(k, selfref=ref(self)):
[2024-03-20T14:04:25.003+0000] {logging_mixin.py:188} WARNING -   File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2024-03-20T14:04:25.041+0000] {logging_mixin.py:188} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2024-03-20T14:04:25.055+0000] {logging_mixin.py:188} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/airflow/.local/lib/python3.8/site-packages/airflow/example_dags/plugins/workday.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.8.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.8.3/best-practices.html#reducing-dag-complexity, PID: 265
